language: java
jdk:
- oraclejdk8
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_ea884ee24f00_key -iv $encrypted_ea884ee24f00_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- ls
- gpg --import private.key
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && cp .travis.settings-security.xml $HOME/.m2/settings-security.xml && mvn versions:set -DnewVersion=$TRAVIS_TAG    && mvn deploy -P release
  skip_cleanup: true
  on:
    tags: true