language: java
jdk:
- oraclejdk8
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_ea884ee24f00_key -iv $encrypted_ea884ee24f00_iv -in private.key.enc -out private.key -d -gpg --import private.key
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn versions:set -DnewVersion=$TRAVIS_TAG && mvn deploy -P release
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: hdMqyvTzzbeOGM+otG+OwCIR+4EFbwDzICLN9JpbLPsmPs0ZVRIH3nh8kP5n2CJxKzoKK98fM7tO6suF1LCbu5QmQx7l1aZIuuR53vSbWOwjaefKTZ3spneaXErb1ggNuiSuXCl/hn7pAxLB1zJkR7PBi5Ry/eOaqcSkJ2RKQH5J8tw4hhmulHpxRuxIB69q2k8hpSO5wcAtkhW/h6NDaliywb53pm9vyrxmHYCaWIH7aL8F1byYXbqDDsnAb+HYydXVWs+1cN/PA2eOKFAqJrE0jtIJJXO6m15HrGotoeOWeRUlMe6LMgyEwA8LtQrlurxS/RFGuSR7f9tlwOjf1RH2fp37lt79OZmZKWeH2hU6X06tTrL1mE+V0hWV0tnFu6oPuFpxkuSdDrjBkUWUbsr3PPWuoENXg+VltpPp4+6sJBSz/j49LItJrvmmzybaMY5LQX7WqjJuBp/9iUPp2Ds3iJOeEbA9kc4hE945kQZHlpWU/1ceHuCqR5tMpUpbUVsaOKeIb5vn5Bbmn4j9pT6huSBTcmtI8rS15MlAz2yfDcrZa/sHYwD3StpCHf7gH94XLjGBaupx4xDJbDPHP9jG5A/NBMt8KlBi8Ax6eQW3gf+Y2L9zM8U8pUDWEv46TbSCNvMiQLOEnmZYn8xNUKhWaP3hA7wvTrrV55ZcrO4=
  - secure: hbPn3VtRB7kxfapJ+6c00uObwyySvEj1oq7fJQvEpS0fPF4DyBcZeTW8pcHlx/Qjk89DY2DEXqyL5RLcNcb274x7tSnXc4MIBrUuK3dpyzpsoiHg6o4pUegcAi5lr3GEv27JzcqZa3HRVWiLEsuBUEEQbX0F19RaB4J8Ty5ZaVUyNdPCGgt7J6MOOvQtCTuI5xBstejWOtnoufdurlPoj5XrX81xiwt3b66oIOjf9U13F/nKYVgT6E+BFck61g8sf5AoCOWXSzofWAEcliiTVBDiDKitzeg4ExX2owb8iR8a789uc67GLGg4Lce9BCLunek+qSknJ5TTCp5FvZ8qodBXCMj9aXphYReO9eI5AhK1B5o/n71+aJ0Qd6Z/ARkiwE7kL3mnnC9VYavdJoZT0LTLQZU1prvYMcoRmlCQDCu5Uz3Gw4J7YEq4LGbCvDfuZ+BQ5pejtGlb6nk25FSKGO0V9Wm7AtVpLwOwaK+op74ZQiQN821PRAdiZ4AvpePEgNGgCzjZ5NPKiTNPIqbxFiLQg4/2WaQN+HXsj9BCPwTXSilb6+deTCVvNE68Xo1zqqfr/8Sa+8UU2E3R48FHaR0XQaCUojhkwC/DPqrMK414FZl2ll5/f53Ouz9SUnKiPxeANqbenFNnK0bvs4UpLJmLynHabplehhA+/LNznko=
